language: python

before_install:
   - pip install -q awscli Pygments

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.82.0/hugo_0.82.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

script:
  - hugo check
  - hugo

deploy:
  provider: script
  script: aws s3 sync --acl public-read --delete public/ s3://family.chadwick.nz
  skip_cleanup: true
  on:
    branch: main

notifications:
  email:
    on_failure: always
